; Type of Token

identifier ::= id_start id_continue*
id_start ::= "_" | lc_letter | uc_letter
id_continue ::= "_" | lc_letter | uc_letter | digit


keyword ::= "if" | "eles" | "while" | "for" | "continue" | "break" | "func" | "return" | "pass" | "var"


literal ::= string_literal | number_literal
string_literal ::= '"' (lc_letter | uc_letter | other_letter)* '"' | "'" (lc_letter | uc_letter | other_letter)* "'"
number_literal ::= integer
lc_letter ::= "a"..."z"
uc_letter ::= "A"..."Z"
integer ::= digit (digit)*
digit ::= "0"..."9"


operator ::= "+" | "-" | "*" | "/" | "%" | "<" | ">" | "<=" | ">=" | "==" | "!=" | "=" | "&&" | "||"


delimiter ::= "(" | ")" | "[" | "]" | "{" | "}" | "," | ":" | "." | indent | "\n" | "\x1A"
indent ::= "\t" | <multiple of indent number of " ">


; Syntax definition

statement ::= VariableDeclaration | FunctionDeclaration | ReturnStatement | ExpressionStatement | IfStatement | ForStatement
VariableDeclaration ::= "var" identifier "=" expression
FunctionDeclaration ::= "func" identifier "(" parameters "):" statement
ReturnStatement ::= "return" expression
ExpressionStatement ::= expression
IfStatement ::= "if" expression ":" statement
ForStatement ::= "for" expression "," expression "," expression ":" statement
parameters ::= (identifier) ("," identifier)*


expression ::= PrimaryExpression | BinaryExpression | AssignExpression | CallExpression
PrimaryExpression ::= identifier | literal
UnarayExpression ::= operator expression
BinaryExpression ::= expression operator expression
AssignExpression ::= identifier "=" expression
CallExpression ::= id "(" arguments ")"
arguments ::= (expression) ("," expression)*
