identifier ::= id_start id_continue*
id_start ::= "_" | lc_letter | uc_letter
id_continue ::= "_" | lc_letter | uc_letter | digit

keyword ::= "if" | "eles" | "while" | "for" | "continue" | "break" | "func" | "return" | "and" | "or" | "pass"

literal ::= string_literal | number_literal
string_literal ::= '"' (lc_letter | uc_letter | other_letter)* '"'
lc_letter ::= "a"..."z"
uc_letter ::= "A"..."Z"
number_literal ::= integer
integer ::= digit (digit)*
digit ::= "0"..."9"

operator ::= "+" | "-" | "*" | "/" | "%" | "<" | ">" | "<=" | ">=" | "==" | "!="

delimiter ::= "(" | ")" | "[" | "]" | "{" | "}" | "," | "." | "\t"